[package]
name = "naval"
version = "0.2.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
strum = { version = "0.27.2", features = ["derive"] }
strum_macros = "0.27.2"
thiserror = "2.0.17"
ratatui = "0.30.0"
crossterm = "0.29.0"

[dev-dependencies]
rstest = "0.26.1"

